apiVersion: v1
kind: ReplicationController
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    app: eureka
  template:
    metadata:
      name: eureka
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: registry.cn-shanghai.aliyuncs.com/ouyangkongli/test:v2
          # image: eureka-docker:latest
          ports:
            - containerPort: 8761
                    