apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: eureka
  type: NodePort
  ports:
  - port: 8761
    nodePort: 30002
  - port: 8762
    nodePort: 30003
  - port: 8763
    nodePort: 30004
